"""initial_schema

Revision ID: 960c802e1fd6
Revises: 
Create Date: 2026-02-28 18:41:06.423870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '960c802e1fd6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('niche', sa.String(length=100), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=100), nullable=True),
    sa.Column('oauth_credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('caption_style', sa.String(length=50), nullable=False),
    sa.Column('thumbnail_style', sa.String(length=50), nullable=False),
    sa.Column('posting_frequency', sa.String(length=50), nullable=False),
    sa.Column('optimal_post_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_channel_id')
    )
    op.create_table('niche_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_audience', sa.String(length=255), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competitor_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_pillars', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('avoid_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_voice_style', sa.String(length=100), nullable=True),
    sa.Column('thumbnail_style', sa.String(length=50), nullable=False),
    sa.Column('posting_frequency', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('content_calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', name='calendarstatus'), nullable=False),
    sa.Column('priority_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('niche_category', sa.String(length=100), nullable=True),
    sa.Column('is_trending', sa.Boolean(), nullable=False),
    sa.Column('is_evergreen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('RESEARCHING', 'SCRIPTING', 'VOICEOVER', 'COLLECTING_ASSETS', 'GENERATING_CAPTIONS', 'GENERATING_THUMBNAIL', 'ASSEMBLING', 'OPTIMIZING_SEO', 'UPLOADING', 'PUBLISHED', 'FAILED', 'QUEUED', name='videostatus'), nullable=False),
    sa.Column('pipeline_step', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('script_text', sa.Text(), nullable=True),
    sa.Column('voiceover_path', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('final_video_path', sa.String(length=500), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('api_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('STOCK_VIDEO', 'AI_IMAGE', 'MUSIC', 'SFX', 'FONT', name='assettype'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('license_type', sa.String(length=100), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('dislikes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('watch_time_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('avg_view_duration', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('avg_view_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ctr', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('subscribers_gained', sa.Integer(), nullable=False),
    sa.Column('estimated_revenue', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('traffic_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('demographics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_analytics')
    op.drop_table('assets')
    op.drop_table('videos')
    op.drop_table('content_calendar')
    op.drop_table('niche_configs')
    op.drop_table('channels')
    # ### end Alembic commands ###
